# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class MicrosoftTtsParams(UncheckedBaseModel):
    """
    Microsoft Azure TTS configuration parameters.
    """

    key: str = pydantic.Field()
    """
    Microsoft Azure API key
    """

    region: str = pydantic.Field()
    """
    Azure region (e.g., "eastus")
    """

    voice_name: str = pydantic.Field()
    """
    Voice name (e.g., "en-US-AndrewMultilingualNeural")
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sampling rate in Hz
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
