# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class RimeTtsParams(UncheckedBaseModel):
    """
    Rime TTS configuration parameters.
    """

    key: str = pydantic.Field()
    """
    Rime API key
    """

    speaker: str = pydantic.Field()
    """
    Rime speaker ID
    """

    model_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model ID (optional)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
