# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx

from .client import Agora as BaseAgora
from .client import AsyncAgora as BaseAsyncAgora
from .core.domain import Area, Pool


class Agora(BaseAgora):
    """
    Agora extends the base client with domain pool support for
    regional URL cycling and automatic domain selection.

    This client automatically:
    - Selects the best domain based on DNS resolution
    - Cycles through region prefixes on request failures
    - Supports US, EU, AP, and CN areas

    Parameters
    ----------
    area : Area
        The area to use for regional URL selection.

    username : typing.Union[str, typing.Callable[[], str]]
    password : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from agoraio import Agora, Area

    client = Agora(
        area=Area.US,
        username="YOUR_USERNAME",
        password="YOUR_PASSWORD",
    )
    """

    def __init__(
        self,
        *,
        area: Area,
        username: typing.Union[str, typing.Callable[[], str]],
        password: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        self._pool = Pool(area)
        super().__init__(
            base_url=self._pool.get_current_url(),
            username=username,
            password=password,
            headers=headers,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
        )

    @property
    def pool(self) -> Pool:
        """
        Get the underlying domain pool for advanced usage.
        You can use this to manually cycle regions or select the best domain.
        """
        return self._pool

    def next_region(self) -> None:
        """
        Cycle to the next region prefix in the pool.
        Call this when a request fails to try a different region.
        """
        self._pool.next_region()
        self._update_base_url()

    def select_best_domain(self) -> None:
        """
        Select the best domain using DNS resolution.
        This is automatically called periodically, but you can call it manually.
        """
        self._pool.select_best_domain()
        self._update_base_url()

    def get_current_url(self) -> str:
        """
        Get the current URL being used for requests.
        """
        return self._pool.get_current_url()

    def _update_base_url(self) -> None:
        """
        Update the base URL in the client wrapper to match the pool's current URL.
        """
        self._client_wrapper._base_url = self._pool.get_current_url()


class AsyncAgora(BaseAsyncAgora):
    """
    AsyncAgora extends the base async client with domain pool support for
    regional URL cycling and automatic domain selection.

    This client automatically:
    - Selects the best domain based on DNS resolution
    - Cycles through region prefixes on request failures
    - Supports US, EU, AP, and CN areas

    Parameters
    ----------
    area : Area
        The area to use for regional URL selection.

    username : typing.Union[str, typing.Callable[[], str]]
    password : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from agoraio import AsyncAgora, Area

    client = AsyncAgora(
        area=Area.US,
        username="YOUR_USERNAME",
        password="YOUR_PASSWORD",
    )
    """

    def __init__(
        self,
        *,
        area: Area,
        username: typing.Union[str, typing.Callable[[], str]],
        password: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        self._pool = Pool(area)
        super().__init__(
            base_url=self._pool.get_current_url(),
            username=username,
            password=password,
            headers=headers,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
        )

    @property
    def pool(self) -> Pool:
        """
        Get the underlying domain pool for advanced usage.
        You can use this to manually cycle regions or select the best domain.
        """
        return self._pool

    def next_region(self) -> None:
        """
        Cycle to the next region prefix in the pool.
        Call this when a request fails to try a different region.
        """
        self._pool.next_region()
        self._update_base_url()

    async def select_best_domain(self) -> None:
        """
        Select the best domain using DNS resolution (async).
        This is automatically called periodically, but you can call it manually.
        """
        await self._pool.select_best_domain_async()
        self._update_base_url()

    def get_current_url(self) -> str:
        """
        Get the current URL being used for requests.
        """
        return self._pool.get_current_url()

    def _update_base_url(self) -> None:
        """
        Update the base URL in the client wrapper to match the pool's current URL.
        """
        self._client_wrapper._base_url = self._pool.get_current_url()
